apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 27.0.2
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  values:
    deployment:
      replicas: 1
    service:
      enabled: false   # disable LB service
    ports:
      web:
        port: 80
        expose: true
        exposedPort: 80
        hostPort: 80
        redirectTo: websecure
      websecure:
        port: 443
        expose: true
        exposedPort: 443
        hostPort: 443
        tls:
          enabled: true
    providers:
      kubernetesCRD: {}
      kubernetesIngress: {}
    ingressClass:
      enabled: true
      isDefaultClass: true
    additionalArguments:
      - --api.dashboard=true
    ingressRoute:
      dashboard:
        enabled: false