apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: 1.14.2
      sourceRef:
        kind: HelmRepository
        name: harbor-charts
        namespace: flux-system
  values:
    expose:
      type: clusterIP
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: harbor-tls

    externalURL: https://harbor-bay.centerionware.com

    harborAdminPassword: Harbor12345
    secretKey: iLjgzLfn7nKGFbXewM4c6q4yvUqpVQSRk5MR9V3axNavubXPw6

    persistence:
      enabled: true
      resourcePolicy: keep
      persistentVolumeClaim:
        registry:
          accessMode: ReadWriteMany
          size: 1Ti
          storageClass: csi-cephfs-sc
        chartmuseum:
          enabled: false
        jobservice:
          accessMode: ReadWriteMany
          size: 10Gi
          storageClass: csi-cephfs-sc
        database:
          accessMode: ReadWriteOnce
          size: 10Gi
          storageClass: csi-cephfs-sc
        redis:
          accessMode: ReadWriteOnce
          size: 5Gi
          storageClass: csi-cephfs-sc
        trivy:
          accessMode: ReadWriteMany
          size: 20Gi
          storageClass: csi-cephfs-sc

    notary:
      enabled: false

    portal:
      replicas: 1
    core:
      replicas: 1
    jobservice:
      replicas: 1
    registry:
      replicas: 1
    chartmuseum:
      enabled: false
    trivy:
      replicas: 1