apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: 1.14.2
      sourceRef:
        kind: HelmRepository
        name: harbor-charts
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: harbor-values
      valuesKey: values.yaml