apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-reflector
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kubernetes-reflector
      version: v9.1.25
      sourceRef:
        kind: GitRepository
        name: emberstack
        namespace: flux-system
  values:
    replicaCount: 1
    img:
      tag: 9.1.25