apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/centerionware/homelab.git
  ref:
    branch: harborbay